services:
  forge:
    image: itzg/minecraft-server:java17
    container_name: mc_forge
    tty: true
    stdin_open: true
    environment:
      ENABLE_ROLLING_LOGS: "TRUE"

      MEMORY: "5000M"
      JVM_OPTS: "-Djava.io.tmpdir=/data/tmp"

      TYPE: "FORGE"
      EULA: "TRUE"
      VERSION: "1.20.1"
      FORGEVERSION: "47.4.4"
      MOTD: "The World of Forge Server"
      MAX_PLAYERS: 5
      MAX_WORLD_SIZE: 10000
      ENABLE_COMMAND_BLOCK: "TRUE"
      SNOOPER_ENABLED: "FALSE"
      VIEW_DISTANCE: 8
      SIMULATION_DISTANCE: 8
      SYNC_CHUNK_WRITES: "FALSE"
      PVP: "TRUE"
      DIFFICULTY: "normal"
      LEVEL: "world"
      ALLOW_FLIGHT: "TRUE"
      USE_NATIVE_TRANSPORT: "TRUE"
      STOP_SERVER_ANNOUNCE_DELAY: 30
      GUI: "FALSE"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      OPS: ""
      SERVER_PORT: "25565"
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    volumes:
      - ./1.20.1:/data
      - /etc/timezone:/etc/timezone:ro
    tmpfs:
      - /tmp:rw,exec,nosuid,nodev,mode=1777,size=1g

    restart: unless-stopped
